In [1]:
"""
날짜 : 2020/08/10
이름 : 이성진
내용 : Numpy 행렬 실습하기

"""

'\n날짜 : 2020/08/10\n이름 : 이성진\n내용 : Numpy 행렬 실습하기\n\n'

In [3]:
import numpy as np

In [62]:
#행렬생성
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m3 = np.ones([2,4])
m4 = np.zeros([3,2])

In [6]:
m1

array([[1, 2],
       [3, 4]])

In [40]:
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
m3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
#행렬 인덱싱
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [21]:
matrix[0,0]

1

In [22]:
matrix[0, :]

array([1, 2, 3, 4])

In [24]:
matrix[1, :]

array([5, 6, 7, 8])

In [25]:
matrix[:,0]

array([1, 5, 9])

In [26]:
matrix[:, 0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [27]:
matrix[:, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [71]:
matrix[:, 0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [67]:
matrix[:, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [69]:
matrix[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [70]:
matrix[1:3, 1:4]

array([[ 6,  7,  8],
       [10, 11, 12]])